# Generated by Django 4.2.7 on 2023-12-05 06:01

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, default='static/img/grid/grid_1.png', null=True, upload_to=home.models.unique_name),
        ),
    ]
