# Generated by Django 4.2.7 on 2023-12-05 06:12

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_courses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/avt.jpg', null=True, upload_to=home.models.unique_name),
        ),
    ]
