# Generated by Django 4.2.7 on 2023-12-06 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_lesson_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lesson',
            new_name='Lessons',
        ),
    ]
