# Generated by Django 4.2.7 on 2023-12-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(help_text='Thumbnail location name', max_length=250),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.CharField(help_text='Video location name', max_length=250),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_upload_url',
            field=models.CharField(help_text='Video location name', max_length=250),
        ),
    ]
