# Generated by Django 4.2.7 on 2023-12-14 06:05

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_reviews_id_alter_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='course_name', unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
