# Generated by Django 4.2.7 on 2023-12-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_courses_slug_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_date',
            field=models.DateField(auto_now=True),
        ),
    ]
